/*
 * This is main Starting page of Student Enrollment application. 
 * In which system user do login with User name and password.
 */

/*
 * Login.java
 *
 */

package WSU_Enrolment;

//Importing java library
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;

public class Login extends javax.swing.JFrame {
	//Unique identifier for class
	private static final long serialVersionUID = 1L;
	// Variables declaration
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;

	//Identify if User is a Student or Administrator
	private static String userProfile;

	/** Creates new form Login */
	public Login() {
		initComponents();
		//Centralize screen
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	/**
	 * @param args the command line arguments
	 * Main method declaration.
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}
	/**
	 * Validate user name and password entered from Jframe user interface
	 */
	public void loginUser(){
		boolean accept=false;
		// Read inputs from text field 
		String username=jTextField1.getText();
		char[] password=jPasswordField1.getPassword();
		// validate user name and password
		if (confirmLogin(username,password)) {
			accept=true;
		}
		if (accept==true){
			//Close login Frame
			this.setVisible(false);
			// Check profile for Administrator and student open user Information frame
			if (userProfile.equalsIgnoreCase("student")){
				JFrame menu=new Menu(username);
				menu.setVisible(true);
			}
			else {
				JFrame menu=new MenuAdmin(username);
				menu.setVisible(true);
			}
		} else
			// Password was incorrect so that alert prompted to user
			JOptionPane.showMessageDialog(null, "Your Login or password are incorrect", "Error", JOptionPane.ERROR_MESSAGE);
	}

	public static boolean confirmLogin(String login, char[] password){
		// Create Database Object
		DAO dao = new DAO();
		ResultSet rs;
		try {
			// connect to database
			dao.connect();
			// Get User Information 
			rs = dao.getResultSet("SELECT password, profile FROM ESU_User WHERE username = '"+login+"'");
			// Return the user match if found otherwise return false
			if (rs.next()) {
				userProfile = rs.getString("profile");
				if (rs.getString("password").equalsIgnoreCase(new String(password))) {
					return true;
				}
				else {
					return false;
				}
			}
		}catch (Exception e){
			// Print SQl exception
			e.printStackTrace();
		}
		return false;  
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();

		jPanel1.setBackground(Color.LIGHT_GRAY);

		jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48));
		jLabel1.setForeground(new java.awt.Color(0, 0, 102));
		jLabel1.setText("Eastern Sydney University");
		jLabel1.setMaximumSize(new java.awt.Dimension(31, 14));
		jLabel1.setPreferredSize(new java.awt.Dimension(31, 14));

		jTextField1.setMaximumSize(new java.awt.Dimension(6, 20));
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new Font("Tahoma", Font.BOLD, 20));
		jLabel2.setText("LOGIN");

		jLabel3.setFont(new Font("Tahoma", Font.BOLD, 20));
		jLabel3.setText("PASSWORD");

		jButton2.setText("LOGIN");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
		jLabel4.setText("Welcome to the Enrolment System");

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
		jLabel5.setText("Login to access");

		jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(60)
										.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 661, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(216)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addComponent(jLabel5)
												.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 337, GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(227)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(315)
										.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(93, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(42)
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jLabel4)
						.addGap(46)
						.addComponent(jLabel5)
						.addGap(39)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addGap(42)
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(61, Short.MAX_VALUE))
				);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 814, GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 453, GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextField1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		loginUser();
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
		// TODO add your handling code here:
		loginUser();
	}//GEN-LAST:event_jPasswordField1ActionPerformed

}
